Feature/add scm filters for branch and pr separately
jenkinsci/scm-filter-branch-pr-plugin pull request #8
Opened 2021-11-19 07:02 UTC by ThejashwiniSwamy

- [ ] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [ ] Ensure that the pull request title represents the desired changelog entry
- [ ] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

2022-10-17 18:30 UTC, nrayapati commented
Thank you for making this PR @ThejashwiniSwamy.

Really appreciate if someone can help review this change and have it available as a release. Thank you very much in advance!

2023-04-30 05:25 UTC, jonesbusy requested changes

2023-04-30 05:25 UTC, jonesbusy commented on src/main/java/net/gleske/scmfilter/impl/trait/RegexSCMBranchFilterTrait.java
> +    @Symbol("RegexSCMBranchFilter")
Better to start symbol with lower case

2023-04-30 05:25 UTC, jonesbusy commented on src/main/java/net/gleske/scmfilter/impl/trait/RegexSCMPRDestinationFilterTrait.java
> +    @Symbol("RegexSCMPRDestinationFilter")
lower case symbol

2023-04-30 05:25 UTC, jonesbusy commented on src/main/java/net/gleske/scmfilter/impl/trait/RegexSCMPROriginFilterTrait.java
> +    @Symbol("RegexSCMPROriginFilter")
This is a breaking change

2023-04-30 05:26 UTC, jonesbusy commented
Hi,

I took over minimal maintenance of this plugin.

This PR introduce breaking changes.

I'm totally fine to introduce new traits to separate branch and PR filtering. 

But we should not break compatibility with user already using those traits. 

Also adding tests would be appreciated.

Best regards,

2023-04-30 05:28 UTC, jonesbusy commented
Also please rebase your PR on main

2023-07-26 01:39 UTC, samrocketman commented
This is a major refactor of existing functionality.  You could add a checkbox so that the filter applies only to pull requests and not branches.

There's no need to have a separate filter just for branches.  The existing SCM branch filter already covers filtering by branch.  This plugin provides a gap that the branch scm filter did not meet (PRs destined for branch).

If you want this to optionally apply to only PRs then the right approach is to introduce a new checkbox to the UI which applies only to pull requests and not branches.

This refactor would duplicate existing core functionality with exception for the purpose this plugin provides (PRs based on source or destination branch).

2023-10-19 23:09 UTC, samrocketman commented
Closing since it would duplicate the built in branch filters provided by core pipeline.

If you think I misunderstood the feature feel free to reply to my comments.

2023-10-19 23:09 UTC, closed without merging

2024-05-31 14:03 UTC, nrayapati commented
@samrocketman, @jonesbusy  we're trying to achieve a similar functionality to the author of this closed PR. We'd like to organize our builds into separate folders based on the branch type:

* Main Folder: Contains the `main` build and PR builds for the `main` branch.
* Releases Folder: Contains builds for all `release-*` branches and their associated PR builds.
* Dev Folder: Contains all remaining builds.

Could you please guide us on how to configure the current version of this plugin to support this use case without including the changes from the closed PR? We'd appreciate any options or settings we can leverage to implement this folder structure without modifying the plugin itself.

Thank you for maintaining this awesome plugin!